# Book settings
title: Quantitative analysis and simulation of mitochondrial energetics
author: Randall, E. Benjamin; Hock, Marcus; Lopez, Rachel; Marshall, Collin; Marzban, Bahador; Beard, Daniel
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex
